// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvooifhbxxoxkwlciiik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2b29pZmhieHhveGt3bGNpaWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwNDU2MTMsImV4cCI6MjA4OTYyMTYxM30.7n863gLe_uF-CTEnD0GhRou3DVBYz-Ul_Zm6NhUJ9wY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});